### PR TITLE
add pokeRadar by benjy3gg

### PR DESCRIPTION
**Pull request by benjy3gg**
Added my pokeRadar map :)

### CODE REVIEW

**Comment by keyphact** [comment]
Hi @benjy3gg,

Thanks for this.
Can we refrain from putting author names in the main link name please?
And also make sure the list is still in its alphabetical state?

**Comment by keyphact** [comment]
Closing this off, until I hear anything back.

**Comment by benjy3gg** [comment]
Hi. Yes sure you can remove my name. No Problem. Can you reopen and merge? Ty for maintaining this!!!

**Comment by keyphact** [comment]
In order to prevent this from conflicting, I will merge this PR for now, and edit it manually.

Thanks

**Pull request merged**
