### PR TITLE
Add Go project to README.md

### PR DESCRIPTION
**Pull request by zeevallin**
Working on a Go implementation, hope you don't mind me adding it to the list.

### CODE REVIEW

**Comment by keyphact** [comment]
Not at all, funny enough I also started working on one, might join efforts and work on yours if you've gotten protobuf files working.

**Comment by zeevallin** [comment]
@keyphact Yeah, got it working a few hours ago. I managed to to get exports working with https://github.com/AeonLucid/POGOProtos and I'm currently providing them [as a package](https://github.com/zeeraw/pogo-protos). And it would be awesome if you want to help out, I'm using this as a practice exercise to learn more Go. :)

**Comment by keyphact** [comment]
Bloody brilliant, would you care to work on this from an organization? and I can give all the admin access you need? I'll also update the reddit thread.

**Comment by zeevallin** [comment]
@keyphact Absolutely! That sounds great.

**Comment by zeevallin** [comment]
@keyphact Name? "pogogo"? xD

**Comment by keyphact** [comment]
I actually don't mind, I started calling mine PokeGo, but I don't mind too much.

Pogogo sounds catchy and funny, so we could go with that :) !

**Comment by zeevallin** [comment]
@keyphact Do you want me to set it up, or are you on it?

**Comment by keyphact** [comment]
I've created an organization for maintaining the awesome-pokemongo list, so we might as well use the same one, have invited you.

https://github.com/pkmngo-odi

**Comment by zeevallin** [comment]
@keyphact Transferred the repositories and fixed their import paths.

**Pull request merged**
